### ISSUE TITLE
4.x addBodyParsingMiddleware can't load default content-Type

### ISSUE THREAD

**Issue by twocolors** [slimphp/Slim#2829] opened 2019-09-06 18:59 UTC
```php
<?php
// use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;
use Slim\Psr7\Response;

require __DIR__ . '/../app/vendor/autoload.php';

$app = AppFactory::create();
$app->addRoutingMiddleware();
$app->addBodyParsingMiddleware();
$app->addErrorMiddleware(true, true, true);

$app->post('/', function (Request $request, Response $response, $args) {
    $json = $request->getParsedBody();
    $response->getBody()->write(var_dump($json));
    return $response;
});

$app->run();
```

this error ...

```
$curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json;charset=utf-8" -X POST http://localhost:8080/
<pre class='xdebug-var-dump' dir='ltr'>
<small>/var/www/html/public/index.php:16:</small><font color='#3465a4'>null</font>
</pre><html>   <head>       <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>       <title>Slim Application Error</title>       <style>           body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif}           h1{margin:0;font-size:48px;font-weight:normal;line-height:48px}           strong{display:inline-block;width:65px}       </style>   </head>   <body>       <h1>Slim Application Error</h1>       <div><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> TypeError</div><div><strong>Code:</strong> 0</div><div><strong>Message:</strong> fwrite() expects parameter 2 to be string, null given</div><div><strong>File:</strong> /var/www/html/app/vendor/slim/psr7/src/Stream.php</div><div><strong>Line:</strong> 319</div><h2>Trace</h2><pre>#0 /var/www/html/app/vendor/slim/psr7/src/Stream.php(319): fwrite(Resource id #6, NULL)
#1 /var/www/html/public/index.php(16): Slim\Psr7\Stream-&gt;write(NULL)
#2 /var/www/html/app/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(42): {closure}(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#3 /var/www/html/app/vendor/slim/slim/Slim/Routing/Route.php(372): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke(Object(Closure), Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array)
#4 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\Routing\Route-&gt;handle(Object(Slim\Psr7\Request))
#5 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#6 /var/www/html/app/vendor/slim/slim/Slim/Routing/Route.php(333): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#7 /var/www/html/app/vendor/slim/slim/Slim/Routing/RouteRunner.php(65): Slim\Routing\Route-&gt;run(Object(Slim\Psr7\Request))
#8 /var/www/html/app/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(58): Slim\Routing\RouteRunner-&gt;handle(Object(Slim\Psr7\Request))
#9 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\RoutingMiddleware-&gt;process(Object(Slim\Psr7\Request), Object(Slim\Routing\RouteRunner))
#10 /var/www/html/app/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(50): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
#11 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\BodyParsingMiddleware-&gt;process(Object(Slim\Psr7\Request), Object(class@anonymous))
#12 /var/www/html/app/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(89): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
#13 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(132): Slim\Middleware\ErrorMiddleware-&gt;process(Object(Slim\Psr7\Request), Object(class@anonymous))
#14 /var/www/html/app/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): class@anonymous-&gt;handle(Object(Slim\Psr7\Request))
#15 /var/www/html/app/vendor/slim/slim/Slim/App.php(206): Slim\MiddlewareDispatcher-&gt;handle(Object(Slim\Psr7\Request))
#16 /var/www/html/app/vendor/slim/slim/Slim/App.php(190): Slim\App-&gt;handle(Object(Slim\Psr7\Request))
#17 /var/www/html/public/index.php(20): Slim\App-&gt;run()
#18 {main}</pre></div>       <a href="#" onClick="window.history.go(-1)">Go Back</a>   </body></html>
```

**Comment by kaxias** [comment] 2019-09-07 01:46
it is your response
```
use Psr\Http\Message\ResponseInterface;
```
try this.

```
$json = json_encode($request->getParsedBody());
        $response->getBody()->write($json);
        return $response
            ->withHeader('Content-Type', 'application/json')
            ->withStatus(201);
```

slim doc
[http://www.slimframework.com/docs/v4/objects/response.html](http://www.slimframework.com/docs/v4/objects/response.html)

**Comment by twocolors** [comment] 2019-09-09 18:55
hm, mb empty getParsedBody ?

**Comment by odan** [comment] 2019-09-09 19:33
I guess the problem is the curl command here. 

This command will send an invalid json request body:

```
curl -X POST -H "Content-Type: application/json" -d '{"key1":"value1","key2":"value2"}' http://localhost:8080
```

This is not a valid JSON request:

```json
'{key1:value1,key2:value2}'
```

The expected http body should be look like this:

```json
{"key1":"value1","key2":"value2"}
```

At the end, this command with escaped `"` and without `'` works on my machine:

```
curl -X POST -H "Content-Type: application/json;charset=utf-8" -d {\"key1\":\"value1\",\"key2\":\"value2\"} http://localhost:8080
```

Now `getParsedBody` returns the correct result:

```php
{"key1":"value1","key2":"value2"}
```

My conclusion: It's an command line (escaping) issue. Slim works correct here, if the request body is valid JSON.

**Comment by l0gicgate** [comment] 2019-09-09 19:54
I'm closing this as resolved. Thanks @odan

**Closed as completed by l0gicgate** 2019-09-09 19:54 UTC
Labels: Slim 4

**Comment by twocolors** [comment] 2019-09-18 08:26
@odan if i add
```
<?php
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Server\RequestHandlerInterface as RequestHandler;
use Slim\Factory\AppFactory;
use Slim\Psr7\Response;

require __DIR__ . '/../app/vendor/autoload.php';

$app = AppFactory::create();
$app->addRoutingMiddleware();
$app->addBodyParsingMiddleware();
$app->addErrorMiddleware(true, true, true);

$app->add(function (Request $request, RequestHandler $handler) {
  $contentType = $request->getHeaderLine('Content-Type');

  if (strstr($contentType, 'application/json')) {
    $contents = json_decode(file_get_contents('php://input'), true);
    if (json_last_error() === JSON_ERROR_NONE) {
      $request = $request->withParsedBody($contents);
    }
  }

  return $handler->handle($request);
});

$app->post('/', function (Request $request, Response $response, $args) {
    $vars = $request->getParsedBody() ?: [];
    var_dump($vars);
    return $response;
});

$app->run();
```
curl work ok, what am I doing wrong ?
```
curl -X POST -H "Content-Type: application/json" -d '{"key1":"value1","key2":"value2"}' http://localhost:8000
<pre class='xdebug-var-dump' dir='ltr'>
<small>/var/www/html/public/index.php:30:</small>
<b>array</b> <i>(size=2)</i>
  'key1' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'value1'</font> <i>(length=6)</i>
  'key2' <font color='#888a85'>=&gt;</font> <small>string</small> <font color='#cc0000'>'value2'</font> <i>(length=6)</i>
```

@l0gicgate reopen issue

**Comment by odan** [comment] 2019-09-20 16:40
@twocolors 

You already added the BodyParsingMiddleware with `$add->addBodyParsingMiddleware()`. Why do you need a second (custom) body parser? Try to remove the custom body parser middeware and then test this command:

```
curl -X POST -H "Content-Type: application/json;charset=utf-8" -d {\"key1\":\"value1\",\"key2\":\"value2\"} http://localhost:8080
```

**Comment by twocolors** [comment] 2019-09-25 15:15
@odan because when i add second (custom) body parser all work ok.
```
$ curl -X POST -H "Content-Type: application/json;charset=utf-8" -d {\"key1\":\"value1\",\"key2\":\"value2\"} http://localhost:8080
curl: (6) Could not resolve host: "key2"
curl: (7) Failed to connect to localhost port 8080: Connection refused
```
sorry i don't understand why we are looking for a problem in **curl** ?!
https://curl.haxx.se/docs/manpage.html#-d
+
https://curl.haxx.se/docs/httpscripting.html#POST
and i use valid json ...
tcdpdum (https://tools.ietf.org/html/rfc8259)
```
POST / HTTP/1.1
User-Agent: curl/7.38.0
Host: localhost
Accept: */*
Content-Type: application/json
Content-Length: 33

{"key1":"value1","key2":"value2"}
```

**Comment by odan** [comment] 2019-09-25 17:12
@twocolors I have tested the curl CLI with the BodyParsingMiddleware successfully. My conclusion was, that it's **not** a Slim and **not** a Curl related issue. It was only a **command line escaping issue** for the `-d {json}` parameter.

> url: (6) Could not resolve host: "key2"

This is what I mean. The console command escaping (of the parameters) is not correct here.

> curl: (7) Failed to connect to localhost port 8080: Connection refused

This is more a local network issue. Maybe your webserver is not running on port 8080.

**Comment by twocolors** [comment] 2019-09-26 12:57
@odan man i use you command. add this error
```
url: (6) Could not resolve host: "key2"
```

**Comment by odan** [comment] 2019-09-26 19:30
It looks like the command line escaping depends on the operating system :P
I have tried your command in a vagrant box with Ubuntu and it works:

```
curl -X POST -H "Content-Type: application/json" -d '{"key1":"value1","key2":"value2"}' http://localhost:8080
```

Result looks good:

```php
array(2) {
  ["key1"]=>
  string(6) "value1"
  ["key2"]=>
  string(6) "value2"
}
```

But I had to fix the code a little bit:

```php
<?php

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;

require_once __DIR__ . '/../vendor/autoload.php';

$app = AppFactory::create();

$app->addRoutingMiddleware();
$app->addBodyParsingMiddleware();
$app->addErrorMiddleware(true, true, true);

$app->post('/', function (Request $request, Response $response, array $args = []) {
    $json = $request->getParsedBody();

    $response->getBody()->write(var_export($json, true));

    return $response;
});

$app->run();
```

Response:

```php
array (
  'key1' => 'value1',
  'key2' => 'value2',
)
```

Changes:

* Replaced `Slim\Psr7\Response` with `Psr\Http\Message\ResponseInterface`
* Changed the function from `var_dump` to `var_export`

I hope it helps.

**Comment by twocolors** [comment] 2019-09-30 15:52
@odan thx, hm  all example and http://www.slimframework.com/ use ### ServerRequestInterface , why i must use ### RequestInterface ? if use ### RequestInterface can\t use ### add

**Comment by odan** [comment] 2019-09-30 17:42
@twocolors Indeed, I confused it with something else. It should be the `Psr\Http\Message\ServerRequestInterface` for the request and `Psr\Http\Message\ResponseInterface` for the response. At the end (in your case) it was just an issue with the `var_dump` function, because the return type of `var_dump` is `void` and not `string`.
https://www.php.net/manual/en/function.var-dump.php
