### ISSUE TITLE
Slim 3.5 PHP errors cause fatal errors in the error handler

### ISSUE THREAD

**Issue by oliverut** [slimphp/Slim#1943] opened 2016-08-01 13:54 UTC
In Slim 3.5 on php 7 I am encountering this php error when Slim attempts to handle php errors:

> `Fatal error: Uncaught TypeError: Argument 1 passed to Slim\Handlers\Error::renderHtmlException() must be an instance of Exception, instance of Error given, called in path/vendor/slim/slim/Slim/Handlers/Error.php on line 84 and defined in path/vendor/slim/slim/Slim/Handlers/Error.php:110 Stack trace: #0 path/vendor/slim/slim/Slim/Handlers/Error.php(84): Slim\Handlers\Error->renderHtmlException(Object(Error)) #1 path/vendor/slim/slim/Slim/Handlers/Error.php(48): Slim\Handlers\Error->renderHtmlErrorMessage(Object(Error)) #2 [internal function]: Slim\Handlers\Error->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(PDOException)) #3 path/vendor/slim/slim/Slim/App.php(613): call_user_func_array(Object(Slim\Handlers\Error), Array) #4 path/vendor/slim/slim/Slim/App.php(339): Slim\App->handleException(Object(PDOExc in path/vendor/slim/slim/Slim/Handlers/Error.php on line 110`

(adjusted to remove paths)

This appears to be this issue: https://akrabat.com/improved-error-handling-in-slim-3-2-0/ (Specfically, the PHP 7 heading)

As I say, I am on Slim 3.5, which I have confirmed through composer and updated just in case. Has this been reverted by accident? 

Here is the method as it appears in my current codebase:

```
protected function renderHtmlException(\Exception $exception)
    {
        $title = 'Slim Application Error';
//more exciting code
```

And the exact composer version: slim/slim 3.5.0 

If it is relevant, I think the error is originating in a PDO class fetch, but its a little difficult to tell.

**Comment by oliverut** [comment] 2016-08-01 14:05
this definately appears to be a revert issue. This change allows the standard slim problem handler to work:

```
protected function renderHtmlException($exception)
    {
        $title = 'Slim Application Error';
//more exciting code
```

**Comment by JoeBengalen** [comment] 2016-08-01 14:20
`Throwable`  should be handled by https://github.com/slimphp/Slim/blob/3.x/Slim/Handlers/PhpError.php

**Comment by oliverut** [comment] 2016-08-01 14:41
I have that class, but it does not appear to be getting involved at any point. This is a pretty fresh install (only a month old) with no previous alterations to error handling so it should be using the defaults, so I am confused if anything else is occurring.

**Comment by JoeBengalen** [comment] 2016-08-01 14:43
Can you look at this line:
https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L341

There the choice is made which error handler to use.

**Comment by oliverut** [comment] 2016-08-01 15:03
My version of that method looks correct. I tested the catches and found this error is being caught by the Exception handler. The $e object type dumps as PDOException with the message 

> General error: could not call class constructor

Which has allowed me to determine that the problem is being inherited from a base class a few layers away at least. (We're migrating our model layer from another framework and it isn't entirely bug free yet).

This doesn't explain why Slim is triggering a fatal error though. From what I can see, the problem is pretty likely in the Error class.

**Comment by akrabat** [comment] 2016-08-01 15:06
Can you provide a minimal code example that shows the problem?

**Comment by oliverut** [comment] 2016-08-01 15:51
OK, this is a relatively minimal example:

In routes:

```
//for orders and related systems
$app->group('/order', function() {
    $this->get('/errorHandleTest', function($request, $response, $args) {
        $pdo = $this->ro_db;
        $orderId = 'UT025SON60.66';

        $baseDataQuery = $pdo->prepare('
            SELECT o.*
            FROM orders AS o
            WHERE o.orders_id = :orderId
        ');
        $baseDataQuery->execute([':orderId' => $orderId]);
        $baseData = $baseDataQuery->fetch(); //using Assoc fetch mode - this makes sense in the full version

        $order = \Models\Slim\OrderTest::loadFromRow($baseData, $pdo);
        $response->write('page');
        return $response;

    });

});
```

In the fetched Model:

```

<?php
namespace Models\Slim;


class OrderTest
{
    private $id;

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }

    public function addItem($item) {
        return true;
    }

    public function initialise($pdo) {

        $orderItemsQuery = $pdo->prepare('
            SELECT * FROM orders_items
            WHERE orders_id = :orderId
        ');
        $orderItemsQuery->setFetchMode(\PDO::FETCH_CLASS, '\Models\Slim\OrderItemTest');
        $orderItemsQuery->execute([':orderId' => $this->getId()]);
        $this->addItem($orderItemsQuery->fetchAll());

        return $this;
    }


    public static function loadFromRow($row, $pdo)
    {
        $order = new OrderTest();
        $order->setId($row['orders_id']);

        $order->initialise($pdo);
        return $order;
    }


}

class OrderItemTest {

    public function __construct()
    {
        parent::__construct(); //deliberate error
    }

}


```

This all basically fetches a row and drops it into a class and then runs an additional query to populate some objects our old model (which is being extended in the real version), which it requires to function. For some reason I couldn't replicate the effect by causing the error in the OrderTest constructor.

I've run out of time to remove the PDO, I'll strip it out if you need me to (although I suspect the PDO is fundamentally the cause).

**Comment by RusAlex** [comment] 2016-08-05 18:23
@oliverut could you cut your minimal working example which can be run by just copy-paste to simple   Slim application ?

**Comment by thiagodp** [comment] 2016-08-26 16:01
@oliverut I think the problem is in your `OrderItemTest`. You should't call `parent::__construct()` when you don't extend any class.

Since this problem has no relation with Slim, I would suggest you to close this issue.

**Comment by chrisemerson** [comment] 2016-11-21 15:31
I'm having this issue now.

It appears to be a problem when you have an Exception that was triggered by a PHP Error. The renderHtmlErrorMessage() method in Slim\Handlers\Error loops around rendering previous exceptions (lines 82 - 85), only it is coming across a PHP 7 Error object instead and then attempting to call renderHtmlException() with it, causing this error.

Changing the typehint on line 110 (for the renderHtmlException method) from 'Exception' to 'Throwable' fixes this. Alternatively some code could determine the type of Throwable that is set as 'previous' on the current Exception, and call the right handler.

**Comment by akrabat** [comment] 2016-11-26 15:21
@chrisemerson can you create a really small test case that shows this?

**Comment by chrisemerson** [comment] 2016-11-26 19:39
$app->get('/test', function ($request, $response, $args) {
        try {
            //Trigger a PHP error - Exceptions since PHP 7, but not a subclass of \Exception, which is the issue
            $myClass = new NonExistantClass();
        } catch (Throwable $ex) {
            throw new Exception("Some new exception wrapping this one", 0, $ex);
        }
    });

**Comment by chrisemerson** [comment] 2016-11-26 19:45
The issue is that Errors are now exceptions in PHP 7, but while they implement Throwable, they don't extend Exception. A third party library I was using caught an error (which was in fact trying to use a class that wasn't loaded I think) and wrapped it in an Exception. The Slim exception handler in Slim\Handlers\Error loops around previous exceptions and tries to render them, but the method that does this type hints for Exception rather than Throwable, so when it gets to the PHP Error at the bottom of the stack it fails the type hint. Changing the type hint to Throwable works, because this covers Error and Exception.

**Comment by akrabat** [comment] 2016-11-26 19:47
We can't change the type hint to Throwable as that won't work in PHP 5.6. Maybe we can remove it?

**Comment by chrisemerson** [comment] 2016-11-26 19:52
The other option is to delegate the rendering back to whatever code picks which of the handlers to use for each error type with a flag to indicate that it's not the first in the stack so it can render 'Previous Exception' correctly, but removing the type hint might be easier!

**Comment by akrabat** [comment] 2017-01-08 11:34
Fixed with PR https://github.com/slimphp/Slim/pull/2121

**Closed as completed** 2017-03-07 16:15 UTC
