### ISSUE TITLE
autoload forms bad paths

### ISSUE THREAD

**Issue by smalpierre** [slimphp/Slim#948] opened 2014-11-25 16:01 UTC
If you move Slim outside of the document root, and / or rename the Slim directory the include path is malformed.

My directory structure is as follows, with Slim in the app directory.

mysite.app
-- app
-- controllers
-- models
--views

mysite.com
-- resources
   -- js
   -- css
   -- img
-- .htacces
-- index.php

The path the autoloader forms to require is something like this - going off memory since I fixed autoload yesterday:

c:/mysite.app/appSlim/Slim.php

It misses the directory separator (not sure why, it works when Slim is in document root and the directory is named Slim ...), and it looks for a Slim subdirectory when there is none.

It does this because it's parsing the namespace wrong. I changed the autoload function in Slim.php and got it working. I did not test to destruction, or use the style guides as my only goal was to make it work - and there are probably much better ways to do this but it's a start:

```
public static function autoload($className) {
    $thisClass = str_replace(__NAMESPACE__ . '\\', '', __CLASS__);

    $baseDir = __DIR__;

    if (substr($baseDir, -strlen($thisClass)) === $thisClass) {
        $baseDir = substr($baseDir, 0, -strlen($thisClass));
    }

    $className = ltrim($className, '\\');
    $fileName = $baseDir;

    $namespace = '';
    if ($lastNsPos = strripos($className, '\\')) {
        $namespace = substr($className, 0, $lastNsPos);
        $className = substr($className, $lastNsPos + 1);

        // HERE BEGINS THE SOLUTION TO THE PROBLEM!
        // Strip everything before the first \ in the class name
        if (($pos = strpos($namespace, '\\')) !== false) {
            $namespace = substr($namespace, $pos + 1);
        }
        // Strip 'Slim' from the namespace name if there is no subnamespace
        if ($namespace === 'Slim') {
            $namespace = '';
        }
        // Add the directory separator to the end of the string if it doesn't exist
        $fileName = rtrim($fileName, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        // Add a test - only do this if $namespace isn't an empty string
        // so it doesn't double the directory separator if $namespace is empty.
        if ($namespace <> '') {
            $fileName .= str_replace('\\', DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
        }
    }
    $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';

    if (file_exists($fileName)) {
        require $fileName;
    }
}
```

**Comment by silentworks** [comment] 2015-02-14 11:23
This is not an issue with Slim itself, it seems more of an issue of the changes you are looking to make. Closing this one off as its not a bug.

**Closed as completed by silentworks** 2015-02-14 11:23 UTC
