### ISSUE TITLE
request->getHeaders() returns HTTP_ uppercased header names

### ISSUE THREAD

**Issue by luispabon** [slimphp/Slim#2760] opened 2019-07-19 16:40 UTC
Given the following slim route:

```php
    // Echo back the request been sent to us
    $app->any('/check/request', function (Request $request, Response $response, array $args) use ($logger) {
        $request->getBody()->rewind();

        $payload = [
            'method'           => $request->getMethod(),
            'body'             => $request->getBody()->getContents(),
            'headers'          => $request->getHeaders(),
            'uri_path'         => $request->getUri()->getPath(),
            'query_parameters' => $request->getQueryParams(),
        ];

        return $response
            ->withHeader('content-type', 'application/json')
            ->withStatus(200)
            ->withBody(stream_for(json_encode($payload)));
    });
```

And the following curl request:

```
curl "localhost:8080/check/request?foo=bar" -XPUT -H"cov: fefe" -d"lalala"
```

The following comes out as a response:

```json
{
    "method": "PUT",
    "body": "lalala",
    "headers": {
        "HTTP_HOST": [
            "localhost:8080"
        ],
        "HTTP_USER_AGENT": [
            "curl\/7.64.0"
        ],
        "HTTP_ACCEPT": [
            "*\/*"
        ],
        "HTTP_COV": [
            "fefe"
        ]
    },
    "uri_path": "\/check\/request",
    "query_parameters": {
        "foo": "bar"
    }
}
```

As you can see, the `cov` header comes out as `HTTP_COV`. Looks like the unfiltered raw PHP SERVER contents right there, which is not what's been sent.

Slim 3.12.1 via php 7.3.7 cli built in server.

**Comment by l0gicgate** [comment] 2019-07-19 18:26
Closing as this is a duplicate of https://github.com/slimphp/Slim-Psr7/issues/103

**Closed as completed by l0gicgate** 2019-07-19 18:26 UTC
