### ISSUE TITLE
In v4 when register a route you must define all path

### ISSUE THREAD

**Issue by RicardoBer** [slimphp/Slim#2786] opened 2019-08-08 17:18 UTC
I tried with apache server, without .htaccess.

I have this path for php script

d:\inetpub\wwwroot\prueba\rest\data.php

I copied "Hello World" example from slim v4 install page.

I install v4 with your composer install instructions.

I must put:
$app->get('/prueba/data.php/', function (Request $request, Response $response, $args) {

I must put full path to work, if I install v3 (with composer) or v2 (clone) it works with only '/' root path, as spected.

I call this url: http://localhost/prueba/data.php/

**Comment by shadowhand** [comment] 2019-08-08 17:39
`data.php` looks like a PHP file, not a callable handler.

**Comment by l0gicgate** [comment] 2019-08-08 19:04
Duplicate of #2784

**Closed as completed by l0gicgate** 2019-08-08 19:04 UTC
Labels: Slim 4
